export const productCards = [
  {
    normalSkin : 'для нормальной кожи',
    image : 'images/moisturizing-mousse.png', 
    title : 'Увлажняющий мус',
    description : 'Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.',
    headerList : 'Состав',
     ingredients : [
      'активные натуральные комплексы',
      'витамины С, А, РР, В И Е',
      'солнцезащитные компоненты',
    ],
    price : '2 750',
  },
  {
    normalSkin : 'для нормальной кожи',
    image : 'images/moisturizing-mask.png',
    title : 'Увлажняющий маска',
    description : 'Способствует удерживанию влаги в верхних слоях кожи.',
    headerList : 'Состав',
    ingredients : [
      'воск',
      'минералы',
      'масла',
    ],
    price : '3 500',
  },
  {
    normalSkin : 'для нормальной кожи',
    image : 'images/cleansing-gel.png',
    title : 'Гель для умывания',
    description : 'Интенсивно очищает, не повреждает защитный барьер кожи.',
    headerList : 'Состав',
    ingredients : [
      'минералы',
      'витамины С, А, РР, В И Е',
      'солнцезащитные компоненты',
    ],
    price : '1 650',
  },
  {
    normalSkin : 'для нормальной кожи',
    image : 'images/gift-set-one.png',
    title : 'Подарочный набор №1',
    description : 'Набор, состоящий из увлажняющего крема и маски.',
    headerList : 'Состав',
    ingredients : [
      'воски',
      'минералы',
      'масла',
    ],
    price : '4 750',
  },
  {
    normalSkin : 'для нормальной кожи',
    image : 'images/gift-set-five.png',
    title : 'Подарочный набор №5',
    description : 'Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.',
    headerList : 'Состав',
    ingredients : [
      'воски',
      'минералы',
      'масла',
    ],
    price : '7 520',
  },
]